/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: "doc",
      id: "welcome-to-masa/welcome-to-masa", // Assuming the document ID you want to link to is structured as `folderName/fileName`.
    },
    {
      type: "category",
      label: "Masa Protocol",
      link: {
        type: "doc",
        // title: "Welcome to Masa Protocol",
        id: "protocol/welcome",
      },
      items: [
        {
          type: "category",
          label: "Oracle Node",
          link: {
            type: "generated-index",
            title: "Oracle Node",
          },
          items: [
            "masa-oracle/oracle-node/introduction",
            "masa-oracle/oracle-node/hardware-network-reqs",
            "masa-oracle/oracle-node/quickstart",
            "masa-oracle/oracle-node/twitter-data",
            "masa-oracle/oracle-node/discord-data",
            "masa-oracle/oracle-node/web-scraper-data",
            "masa-oracle/oracle-node/data-catalog",
            "masa-oracle/oracle-node/twitter-sentiment",
          ],
        },
        {
          type: "category",
          label: "Worker Node",
          link: {
            type: "generated-index",
            title: "Worker Node",
          },
          items: [
            "masa-oracle/worker-node/introduction",
            "masa-oracle/worker-node/quickstart",
            "masa-oracle/worker-node/twitter-worker",
            "masa-oracle/worker-node/discord-worker",
            "masa-oracle/worker-node/web-worker",
          ],
        },
        {
          type: "category",
          label: "Guides and Tutorials",
          link: {
            type: "generated-index",
            title: "Guides and Tutorials",
          },
          items: ["masa-oracle/guides-and-tutorials/staking-guide"],
        },
        {
          type: "category",
          label: "Tools and Contracts",
          link: {
            type: "generated-index",
            title: "Tools & Contracts overview",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "tools-and-contracts",
            },
            {
              type: "category",
              label: "Masa Token",
              link: {
                type: "doc",
                id: "masa-token/README",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "masa-token",
                },
              ],
            },
          ],
        },
        {
          type: "doc",
          label: "Release Notes",
          id: "masa-oracle/RELEASE_NOTES", // Assuming the document ID you want to link to is structured as `folderName/fileName`.
        },
      ],
    },
    {
      type: "category",
      label: "Masa Bittensor Testnet",
      link: {
        type: "doc",
        id: "masa-subnet/incentivized-testnet-event/intro",
      },
      items: [
        "masa-subnet/incentivized-testnet-event/1-create-environment",
        "masa-subnet/incentivized-testnet-event/2-install-packages",
        "masa-subnet/incentivized-testnet-event/3-create-wallet",
        "masa-subnet/incentivized-testnet-event/4-fund-wallet",
        "masa-subnet/incentivized-testnet-event/5-register-wallet",
        "masa-subnet/incentivized-testnet-event/6-run-protocol",
        "masa-subnet/incentivized-testnet-event/7-run-miner",
        "masa-subnet/incentivized-testnet-event/8-check-status",
        "masa-subnet/incentivized-testnet-event/9-register",
        {
          type: "doc",
          label: "10. Run Miner Remotely",
          id: "masa-subnet/runpod/miner",
        },
      ],
    },
    {
      type: "category",
      label: "Masa Bittensor Subnet",
      link: {
        type: "doc",
        id: "masa-subnet/welcome",
      },
      items: [
        {
          type: "category",
          label: "Setup Guide",
          link: {
            type: "doc",
            id: "masa-subnet/setup/intro",
          },
          items: [
            "masa-subnet/setup/1-create-environment",
            "masa-subnet/setup/2-install-packages",
            "masa-subnet/setup/3-create-wallets",
            "masa-subnet/setup/4-fund-wallets",
            "masa-subnet/setup/5-register-wallets",
            "masa-subnet/setup/6-stake-validator",
            "masa-subnet/setup/7-set-weights",
            "masa-subnet/setup/8-run-protocol",
            "masa-subnet/setup/9-run-miner-and-validator",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "doc",
            id: "masa-subnet/advanced/intro",
          },
          items: ["masa-subnet/advanced/known-issues", "masa-subnet/advanced/local-subtensor"],
        },
        {
          type: "doc",
          label: "Release Notes",
          id: "masa-subnet/RELEASE_NOTES", // Assuming the document ID you want to link to is structured as `folderName/fileName`.
        },
      ],
    },
  ],
};

module.exports = sidebars;
